- hosts: cassandra
  sudo: yes
  strategy: free
  tasks:
    - name: download cassandra
      get_url:
        url: https://rpm.datastax.com/community/noarch/cassandra22-2.2.3-1.noarch.rpm
        dest: /tmp/cassandra.rpm
      register: status

    - name: install
      shell: rpm -iUvh /tmp/cassandra.rpm
      when: status.changed

    - template: src=templates/cassandra_defaults.yaml dest=/etc/cassandra/conf/cassandra.yaml
    - template: src=templates/cassandra-env.sh dest=/etc/cassandra/conf/cassandra-env.sh

    - file: path=/cass state=directory owner=cassandra

    - service: name=cassandra state=restarted

    - template: src=templates/stress.yaml dest=/etc/cassandra/conf/stress.yaml
      tags: stress


- include: install_stress_tool.yaml